<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>ru.truhot</groupId>
  <artifactId>Rdang</artifactId>
  <version>1.21.4</version>
  <packaging>jar</packaging>

  <name>Rdang</name>

  <properties>
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <release>21</release>
          <fork>true</fork>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>

  <repositories>
      <repository>
          <id>papermc-repo</id>
          <url>https://repo.papermc.io/repository/maven-public/</url>
      </repository>
      <repository>
          <id>sonatype</id>
          <url>https://oss.sonatype.org/content/groups/public/</url>
      </repository>
      <repository>
          <id>enginehub</id>
          <url>https://maven.enginehub.org/repo/</url>
      </repository>
      <repository>
          <id>playpro</id>
          <url>https://maven.playpro.com</url>
      </repository>
  </repositories>

  <dependencies>
      <dependency>
          <groupId>io.papermc.paper</groupId>
          <artifactId>paper-api</artifactId>
          <version>1.21.4-R0.1-SNAPSHOT</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>com.sk89q.worldedit</groupId>
          <artifactId>worldedit-bukkit</artifactId>
          <version>7.3.10</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>com.sk89q.worldguard</groupId>
          <artifactId>worldguard-bukkit</artifactId>
          <version>7.0.12</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>net.coreprotect</groupId>
          <artifactId>coreprotect</artifactId>
          <version>22.4</version>
          <scope>provided</scope>
      </dependency>
  </dependencies>
</project>
